version: "3"
services:
  db:
    container_name: DB
    image: clearlinux/postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: foprta
      POSTGRES_DB: todo
    ports:
      - 5432:5432

  server:
    container_name: SERVER
    build:
      context: ./server
      dockerfile: Dockerfile
    links:
      - db
    depends_on:
      - db
    ports:
      - 80:80
    expose:
      - 80
    volumes:
      - ./server:/go/src/server

  client:
    container_name: CLIENT
    build:
      context: ./client
      dockerfile: Dockerfile
    links:
      - server
    depends_on:
      - server
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - ./client:/usr/src/client
