export default {
  GET_TODOS: "GET_TODOS",
  GET_TODOS_SUCCESS: "GET_TODOS_SUCCESS",
  GET_TODOS_ERROR: "GET_TODOS_ERROR",

  CHANGE_TODO_STATE: "CHANGE_TODO_STATE",
  CHANGE_TODO_STATE_SUCCESS: "CHANGE_TODO_STATE_SUCCESS",
  CHANGE_TODO_STATE_ERROR: "CHANGE_TODO_STATE_ERROR",

  ADD_TODOS: "ADD_TODOS",
  ADD_TODOS_SUCCESS: "ADD_TODOS_SUCCESS",
  ADD_TODOS_ERROR: "ADD_TODOS_ERROR",
};
