export default {
  GET_WEAPONS: "GET_WEAPONS",
  GET_WEAPONS_SUCCESS: "GET_WEAPONS_SUCCESS",
  GET_WEAPONS_ERROR: "GET_WEAPONS_ERROR",

  SELECT_WEAPON: "SELECT_WEAPON",
  SELECT_WEAPON_SUCCESS: "SELECT_WEAPON_SUCCESS",
  SELECT_WEAPON_ERROR: "SELECT_WEAPON_ERROR",
};
